name: 📊 Static Checks
on: [push, pull_request]

concurrency:
    group: ci-${{ github.actor }}-${{ github.head_ref || github.run_number }}-${{ github.ref }}-static

jobs:
    static-checks:
        name: Code style, file formatting, and XML validation
        runs-on: ubuntu-24.04
        steps:
          - name: Checkout
            uses: actions/checkout@v4
            with:
                fetch-depth: 2

          - name: Setup Node.js
            uses: actions/setup-node@v4
            with:
                node-version: 22

          - name: Install dependencies
            run: npm ci

          - name: Run ESLint
            run: npx eslint --max-warnings=0

          - name: Install APT dependencies for XML validation
            uses: awalsh128/cache-apt-pkgs-action@latest
            with:
                packages: libxml2-utils

          - name: XML validation via xmllint
            run: |
                xmllint --nout data/<TEMPLATE:APPID>.gschema.xml data/<TEMPLATE:APPID>.metainfo.xml.in src/<TEMPLATE:APPID>.data.gresource.xml src/<TEMPLATE:APPID>.src.gresource.xml
